// <auto-generated />
using System;
using ClinicaMedica.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaMedica.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122004145_FixDoctorAgendaRelation")]
    partial class FixDoctorAgendaRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorID");

                    b.ToTable("DoctorAgenda", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorEspecialidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("EspID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("EspID");

                    b.ToTable("DoctorEspecialidad", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorFechasBloqueadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorID", "Fecha")
                        .IsUnique();

                    b.ToTable("DoctorFechasBloqueadas", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorObraSocial", b =>
                {
                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("OSID")
                        .HasColumnType("int");

                    b.HasKey("DoctorID", "OSID");

                    b.HasIndex("OSID");

                    b.ToTable("DoctoresObrasSociales", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Especialidad", b =>
                {
                    b.Property<int>("EspID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspID"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EspID");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Estudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveDownloadLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveFileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveWebViewLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Estudios", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.ObraSocial", b =>
                {
                    b.Property<int>("OSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OSID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OSID");

                    b.ToTable("ObraSocial");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdDoctor", "FechaHora")
                        .IsUnique();

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroSocio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OSID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorAgenda", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Doctor")
                        .WithMany("Agendas")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorEspecialidad", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Doctor")
                        .WithMany("Especialidades")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaMedica.Backend.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorFechasBloqueadas", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.DoctorObraSocial", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Doctor")
                        .WithMany("ObrasSociales")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaMedica.Backend.Models.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("OSID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Estudio", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Turno", b =>
                {
                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Doctor")
                        .WithMany("TurnosComoDoctor")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaMedica.Backend.Models.Usuario", "Paciente")
                        .WithMany("TurnosComoPaciente")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaMedica.Backend.Models.Usuario", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Especialidades");

                    b.Navigation("ObrasSociales");

                    b.Navigation("TurnosComoDoctor");

                    b.Navigation("TurnosComoPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
